// Misc public UI strings in 24 EU locales (previously hardcoded Hungarian leaks).
// hu+en authored; machine-translated + QA-reviewed (lv/lt/mt/sl round-1 hand-translated).
import { type Locale } from '@/lib/i18n/config';

export interface UiStrings {
  added: string;
  chat_error: string;
  chat_connection_error: string;
  back_to_top: string;
  product_unavailable: string;
  cart_demo_note: string;
  err_name_reason_required: string;
  err_reason_min: string;
  err_invalid_email: string;
  edukacio_intro: string;
  edukacio_empty: string;
  product_tax_note: string;
}

const UI_STRINGS: Record<Locale, UiStrings> = {
  hu: {"added":"Hozzáadva","chat_error":"Hiba.","chat_connection_error":"Kapcsolat-hiba. Próbáld újra.","back_to_top":"Vissza a tetejére","product_unavailable":"Termék még nem elérhető","cart_demo_note":"Stripe placeholder-módban:","err_name_reason_required":"Név és indoklás kötelező.","err_reason_min":"Az indoklás legalább 30 karakter legyen.","err_invalid_email":"Érvénytelen email-cím.","edukacio_intro":"Női egészség, hőterápia, önmegfigyelés. Forrásokkal alátámasztott, érthető cikkek. EBC Wellness — független, ingyenes tudás.","edukacio_empty":"Még nincs publikált cikk ebben a kategóriában. Iratkozz fel a hírlevélre — értesítünk!","product_tax_note":"ÁFA-val · szállítás kalkulálva a kosárban"},
  en: {"added":"Added","chat_error":"Error.","chat_connection_error":"Connection error. Please try again.","back_to_top":"Back to top","product_unavailable":"Product not available yet","cart_demo_note":"Stripe is in placeholder mode:","err_name_reason_required":"Name and reason are required.","err_reason_min":"The reason must be at least 30 characters.","err_invalid_email":"Invalid email address.","edukacio_intro":"Women's health, heat therapy, self-awareness. Source-backed, clear articles. EBC Wellness — independent, free knowledge.","edukacio_empty":"No published articles in this category yet. Subscribe to the newsletter — we'll notify you!","product_tax_note":"VAT included · shipping calculated at checkout"},
  de: {"added":"Hinzugefügt","chat_error":"Fehler.","chat_connection_error":"Verbindungsfehler. Bitte versuche es erneut.","back_to_top":"Nach oben","product_unavailable":"Produkt noch nicht verfügbar","cart_demo_note":"Stripe befindet sich im Platzhaltermodus:","err_name_reason_required":"Name und Grund sind erforderlich.","err_reason_min":"Der Grund muss mindestens 30 Zeichen lang sein.","err_invalid_email":"Ungültige E-Mail-Adresse.","edukacio_intro":"Frauengesundheit, Wärmetherapie, Selbstwahrnehmung. Quellenbasierte, verständliche Artikel. EBC Wellness — unabhängiges, kostenloses Wissen.","edukacio_empty":"In dieser Kategorie sind noch keine Artikel veröffentlicht. Abonnieren Sie den Newsletter — wir benachrichtigen Sie!","product_tax_note":"inkl. MwSt. · Versandkosten werden an der Kasse berechnet"},
  fr: {"added":"Ajouté","chat_error":"Erreur.","chat_connection_error":"Erreur de connexion. Veuillez réessayer.","back_to_top":"Haut de page","product_unavailable":"Produit pas encore disponible","cart_demo_note":"Stripe est en mode démonstration :","err_name_reason_required":"Le nom et le motif sont obligatoires.","err_reason_min":"Le motif doit comporter au moins 30 caractères.","err_invalid_email":"Adresse e-mail invalide.","edukacio_intro":"Santé féminine, thérapie par la chaleur, connaissance de soi. Des articles clairs et sourcés. EBC Wellness — un savoir indépendant et gratuit.","edukacio_empty":"Aucun article publié dans cette catégorie pour le moment. Abonnez-vous à la newsletter — nous vous préviendrons !","product_tax_note":"TVA incluse · frais de livraison calculés lors du paiement"},
  it: {"added":"Aggiunto","chat_error":"Errore.","chat_connection_error":"Errore di connessione. Riprova.","back_to_top":"Torna su","product_unavailable":"Prodotto non ancora disponibile","cart_demo_note":"Stripe è in modalità segnaposto:","err_name_reason_required":"Nome e motivo sono obbligatori.","err_reason_min":"Il motivo deve contenere almeno 30 caratteri.","err_invalid_email":"Indirizzo email non valido.","edukacio_intro":"Salute femminile, terapia del calore, consapevolezza di sé. Articoli chiari e basati su fonti attendibili. EBC Wellness — conoscenza indipendente e gratuita.","edukacio_empty":"Non ci sono ancora articoli pubblicati in questa categoria. Iscriviti alla newsletter — ti avviseremo noi!","product_tax_note":"IVA inclusa · spese di spedizione calcolate al checkout"},
  es: {"added":"Añadido","chat_error":"Error.","chat_connection_error":"Error de conexión. Inténtalo de nuevo.","back_to_top":"Volver arriba","product_unavailable":"Producto aún no disponible","cart_demo_note":"Stripe está en modo de prueba:","err_name_reason_required":"El nombre y el motivo son obligatorios.","err_reason_min":"El motivo debe tener al menos 30 caracteres.","err_invalid_email":"Dirección de correo electrónico no válida.","edukacio_intro":"Salud femenina, terapia de calor, autoconocimiento. Artículos claros y con fuentes contrastadas. EBC Wellness — conocimiento independiente y gratuito.","edukacio_empty":"Todavía no hay artículos publicados en esta categoría. Suscríbete al boletín — ¡te avisaremos!","product_tax_note":"IVA incluido · gastos de envío calculados al finalizar la compra"},
  pl: {"added":"Dodano","chat_error":"Błąd.","chat_connection_error":"Błąd połączenia. Spróbuj ponownie.","back_to_top":"Do góry","product_unavailable":"Produkt jeszcze niedostępny","cart_demo_note":"Stripe działa w trybie demonstracyjnym:","err_name_reason_required":"Imię i powód są wymagane.","err_reason_min":"Powód musi mieć co najmniej 30 znaków.","err_invalid_email":"Nieprawidłowy adres e-mail.","edukacio_intro":"Zdrowie kobiet, terapia ciepłem, samoświadomość. Rzetelne, przejrzyste artykuły oparte na źródłach. EBC Wellness — niezależna, bezpłatna wiedza.","edukacio_empty":"W tej kategorii nie ma jeszcze opublikowanych artykułów. Zapisz się do newslettera — damy Ci znać!","product_tax_note":"Cena zawiera VAT · koszt wysyłki obliczany przy zamówieniu"},
  ro: {"added":"Adăugat","chat_error":"Eroare.","chat_connection_error":"Eroare de conexiune. Te rugăm să încerci din nou.","back_to_top":"Înapoi sus","product_unavailable":"Produs indisponibil momentan","cart_demo_note":"Stripe este în mod demonstrativ:","err_name_reason_required":"Numele și motivul sunt obligatorii.","err_reason_min":"Motivul trebuie să aibă cel puțin 30 de caractere.","err_invalid_email":"Adresă de e-mail invalidă.","edukacio_intro":"Sănătatea femeii, terapia prin căldură, autocunoaștere. Articole clare, susținute de surse. EBC Wellness — cunoaștere independentă și gratuită.","edukacio_empty":"Încă nu există articole publicate în această categorie. Abonează-te la newsletter — te anunțăm noi!","product_tax_note":"TVA inclus · transportul se calculează la finalizarea comenzii"},
  nl: {"added":"Toegevoegd","chat_error":"Fout.","chat_connection_error":"Verbindingsfout. Probeer het opnieuw.","back_to_top":"Terug naar boven","product_unavailable":"Product nog niet beschikbaar","cart_demo_note":"Stripe staat in placeholdermodus:","err_name_reason_required":"Naam en reden zijn verplicht.","err_reason_min":"De reden moet minstens 30 tekens bevatten.","err_invalid_email":"Ongeldig e-mailadres.","edukacio_intro":"Vrouwengezondheid, warmtetherapie, zelfbewustzijn. Heldere artikelen, onderbouwd met bronnen. EBC Wellness — onafhankelijke, gratis kennis.","edukacio_empty":"Nog geen gepubliceerde artikelen in deze categorie. Schrijf je in voor de nieuwsbrief — dan brengen we je op de hoogte!","product_tax_note":"Inclusief btw · verzendkosten worden bij het afrekenen berekend"},
  pt: {"added":"Adicionado","chat_error":"Erro.","chat_connection_error":"Erro de ligação. Tente novamente.","back_to_top":"Voltar ao topo","product_unavailable":"Produto ainda não disponível","cart_demo_note":"O Stripe está em modo de demonstração:","err_name_reason_required":"O nome e o motivo são obrigatórios.","err_reason_min":"O motivo deve ter pelo menos 30 caracteres.","err_invalid_email":"Endereço de e-mail inválido.","edukacio_intro":"Saúde da mulher, termoterapia, autoconhecimento. Artigos claros e baseados em fontes. EBC Wellness — conhecimento independente e gratuito.","edukacio_empty":"Ainda não há artigos publicados nesta categoria. Subscreva a newsletter — avisamos quando houver novidades!","product_tax_note":"IVA incluído · portes calculados na finalização da compra"},
  cs: {"added":"Přidáno","chat_error":"Chyba.","chat_connection_error":"Chyba připojení. Zkuste to prosím znovu.","back_to_top":"Zpět nahoru","product_unavailable":"Produkt zatím není dostupný","cart_demo_note":"Stripe je v zástupném režimu:","err_name_reason_required":"Jméno a důvod jsou povinné.","err_reason_min":"Důvod musí mít alespoň 30 znaků.","err_invalid_email":"Neplatná e-mailová adresa.","edukacio_intro":"Zdraví žen, tepelná terapie, sebepoznání. Srozumitelné články podložené zdroji. EBC Wellness — nezávislé, bezplatné znalosti.","edukacio_empty":"V této kategorii zatím nejsou publikované žádné články. Přihlaste se k odběru newsletteru — dáme vám vědět!","product_tax_note":"včetně DPH · doprava se vypočítá při objednávce"},
  sk: {"added":"Pridané","chat_error":"Chyba.","chat_connection_error":"Chyba pripojenia. Skúste to znova.","back_to_top":"Späť nahor","product_unavailable":"Produkt zatiaľ nie je dostupný","cart_demo_note":"Stripe je v režime ukážky:","err_name_reason_required":"Meno a dôvod sú povinné.","err_reason_min":"Dôvod musí mať aspoň 30 znakov.","err_invalid_email":"Neplatná e-mailová adresa.","edukacio_intro":"Zdravie žien, terapia teplom, sebapoznanie. Zrozumiteľné články podložené zdrojmi. EBC Wellness — nezávislé, bezplatné vedomosti.","edukacio_empty":"V tejto kategórii zatiaľ nie sú žiadne publikované články. Prihláste sa na odber noviniek — dáme vám vedieť!","product_tax_note":"Vrátane DPH · doprava sa vypočíta pri pokladni"},
  sv: {"added":"Tillagd","chat_error":"Fel.","chat_connection_error":"Anslutningsfel. Försök igen.","back_to_top":"Till toppen","product_unavailable":"Produkten är inte tillgänglig ännu","cart_demo_note":"Stripe är i platshållarläge:","err_name_reason_required":"Namn och anledning krävs.","err_reason_min":"Anledningen måste vara minst 30 tecken.","err_invalid_email":"Ogiltig e-postadress.","edukacio_intro":"Kvinnors hälsa, värmeterapi, självkännedom. Källbelagda, tydliga artiklar. EBC Wellness — oberoende, kostnadsfri kunskap.","edukacio_empty":"Inga publicerade artiklar i den här kategorin ännu. Prenumerera på nyhetsbrevet — vi meddelar dig!","product_tax_note":"Moms ingår · frakt beräknas i kassan"},
  da: {"added":"Tilføjet","chat_error":"Fejl.","chat_connection_error":"Forbindelsesfejl. Prøv igen.","back_to_top":"Tilbage til toppen","product_unavailable":"Produktet er ikke tilgængeligt endnu","cart_demo_note":"Stripe er i pladsholdertilstand:","err_name_reason_required":"Navn og begrundelse er påkrævet.","err_reason_min":"Begrundelsen skal være på mindst 30 tegn.","err_invalid_email":"Ugyldig e-mailadresse.","edukacio_intro":"Kvinders sundhed, varmeterapi, selvindsigt. Kildebelagte, klare artikler. EBC Wellness — uafhængig, gratis viden.","edukacio_empty":"Der er endnu ingen offentliggjorte artikler i denne kategori. Tilmeld dig nyhedsbrevet — så giver vi dig besked!","product_tax_note":"Moms inkluderet · forsendelse beregnes ved betaling"},
  fi: {"added":"Lisätty","chat_error":"Virhe.","chat_connection_error":"Yhteysvirhe. Yritä uudelleen.","back_to_top":"Takaisin ylös","product_unavailable":"Tuote ei ole vielä saatavilla","cart_demo_note":"Stripe on paikkamerkkitilassa:","err_name_reason_required":"Nimi ja syy ovat pakollisia.","err_reason_min":"Syyn on oltava vähintään 30 merkkiä.","err_invalid_email":"Virheellinen sähköpostiosoite.","edukacio_intro":"Naisten terveys, lämpöterapia, itsetuntemus. Lähteisiin perustuvia, selkeitä artikkeleita. EBC Wellness — riippumatonta, ilmaista tietoa.","edukacio_empty":"Tässä kategoriassa ei ole vielä julkaistuja artikkeleita. Tilaa uutiskirje — me ilmoitamme sinulle!","product_tax_note":"Sis. ALV · toimituskulut lasketaan kassalla"},
  bg: {"added":"Добавено","chat_error":"Грешка.","chat_connection_error":"Грешка във връзката. Моля, опитайте отново.","back_to_top":"Обратно горе","product_unavailable":"Продуктът все още не е наличен","cart_demo_note":"Stripe е в режим на заместване:","err_name_reason_required":"Името и причината са задължителни.","err_reason_min":"Причината трябва да е поне 30 знака.","err_invalid_email":"Невалиден имейл адрес.","edukacio_intro":"Женско здраве, топлинна терапия, самопознание. Ясни статии, подкрепени с източници. EBC Wellness — независимо, безплатно знание.","edukacio_empty":"Все още няма публикувани статии в тази категория. Абонирайте се за бюлетина — ще ви уведомим!","product_tax_note":"С включен ДДС · доставката се изчислява при плащане"},
  hr: {"added":"Dodano","chat_error":"Greška.","chat_connection_error":"Greška veze. Pokušajte ponovno.","back_to_top":"Natrag na vrh","product_unavailable":"Proizvod još nije dostupan","cart_demo_note":"Stripe je u načinu rada za demonstraciju:","err_name_reason_required":"Ime i razlog su obavezni.","err_reason_min":"Razlog mora imati najmanje 30 znakova.","err_invalid_email":"Nevažeća adresa e-pošte.","edukacio_intro":"Žensko zdravlje, terapija toplinom, samosvijest. Jasni članci potkrijepljeni izvorima. EBC Wellness — neovisno, besplatno znanje.","edukacio_empty":"U ovoj kategoriji još nema objavljenih članaka. Pretplatite se na newsletter — obavijestit ćemo vas!","product_tax_note":"PDV uključen · dostava se obračunava pri naplati"},
  et: {"added":"Lisatud","chat_error":"Viga.","chat_connection_error":"Ühenduse viga. Palun proovi uuesti.","back_to_top":"Tagasi üles","product_unavailable":"Toode pole veel saadaval","cart_demo_note":"Stripe on näidisrežiimis:","err_name_reason_required":"Nimi ja põhjus on kohustuslikud.","err_reason_min":"Põhjus peab olema vähemalt 30 tähemärki.","err_invalid_email":"Vigane e-posti aadress.","edukacio_intro":"Naiste tervis, soojusteraapia, eneseteadlikkus. Allikatega kinnitatud, selged artiklid. EBC Wellness — sõltumatu, tasuta teadmus.","edukacio_empty":"Selles kategoorias pole veel avaldatud artikleid. Telli uudiskiri — anname sulle teada!","product_tax_note":"Käibemaks sisaldub · tarne arvutatakse kassas"},
  el: {"added":"Προστέθηκε","chat_error":"Σφάλμα.","chat_connection_error":"Σφάλμα σύνδεσης. Δοκιμάστε ξανά.","back_to_top":"Επιστροφή στην κορυφή","product_unavailable":"Το προϊόν δεν είναι ακόμη διαθέσιμο","cart_demo_note":"Το Stripe είναι σε λειτουργία επίδειξης:","err_name_reason_required":"Το όνομα και ο λόγος είναι υποχρεωτικά.","err_reason_min":"Ο λόγος πρέπει να έχει τουλάχιστον 30 χαρακτήρες.","err_invalid_email":"Μη έγκυρη διεύθυνση email.","edukacio_intro":"Υγεία των γυναικών, θερμοθεραπεία, αυτογνωσία. Σαφή άρθρα, τεκμηριωμένα με πηγές. EBC Wellness — ανεξάρτητη, δωρεάν γνώση.","edukacio_empty":"Δεν υπάρχουν ακόμη δημοσιευμένα άρθρα σε αυτή την κατηγορία. Εγγραφείτε στο newsletter — θα σας ειδοποιήσουμε!","product_tax_note":"Συμπεριλαμβανομένου ΦΠΑ · τα έξοδα αποστολής υπολογίζονται κατά την ολοκλήρωση της παραγγελίας"},
  ga: {"added":"Curtha leis","chat_error":"Earráid.","chat_connection_error":"Earráid cheangail. Bain triail eile as le do thoil.","back_to_top":"Ar ais go barr","product_unavailable":"Níl an táirge ar fáil go fóill","cart_demo_note":"Tá Stripe i mód áitchoinneálaí:","err_name_reason_required":"Tá ainm agus cúis riachtanach.","err_reason_min":"Caithfidh an chúis a bheith 30 carachtar ar a laghad.","err_invalid_email":"Seoladh ríomhphoist neamhbhailí.","edukacio_intro":"Sláinte na mban, teiripe teasa, féinfheasacht. Ailt shoiléire le fhoinsí taca. EBC Wellness — eolas neamhspleách, saor in aisce.","edukacio_empty":"Níl aon alt foilsithe sa chatagóir seo go fóill. Cláraigh don nuachtlitir — cuirfimid in iúl duit!","product_tax_note":"CBL san áireamh · costas seachadta ríofa ag an tseiceáil amach"},
  lv: {"added":"Pievienots","chat_error":"Kļūda.","chat_connection_error":"Savienojuma kļūda. Lūdzu, mēģiniet vēlreiz.","back_to_top":"Atpakaļ uz augšu","product_unavailable":"Produkts vēl nav pieejams","cart_demo_note":"Stripe ir demonstrācijas režīmā:","err_name_reason_required":"Vārds un iemesls ir obligāti.","err_reason_min":"Iemeslam jābūt vismaz 30 rakstzīmes garam.","err_invalid_email":"Nederīga e-pasta adrese.","edukacio_intro":"Sieviešu veselība, siltumterapija, pašizziņa. Skaidri, uz avotiem balstīti raksti. EBC Wellness — neatkarīgas, bezmaksas zināšanas.","edukacio_empty":"Šajā kategorijā vēl nav publicētu rakstu. Abonējiet jaunumu vēstkopu — mēs jums paziņosim!","product_tax_note":"PVN iekļauts · piegāde tiek aprēķināta noformējot pasūtījumu"},
  lt: {"added":"Pridėta","chat_error":"Klaida.","chat_connection_error":"Ryšio klaida. Bandykite dar kartą.","back_to_top":"Atgal į viršų","product_unavailable":"Produktas dar neprieinamas","cart_demo_note":"Stripe veikia demonstraciniu režimu:","err_name_reason_required":"Vardas ir priežastis yra privalomi.","err_reason_min":"Priežastį turi sudaryti bent 30 simbolių.","err_invalid_email":"Neteisingas el. pašto adresas.","edukacio_intro":"Moterų sveikata, šilumos terapija, savęs pažinimas. Aiškūs, šaltiniais pagrįsti straipsniai. EBC Wellness — nepriklausomos, nemokamos žinios.","edukacio_empty":"Šioje kategorijoje dar nėra publikuotų straipsnių. Užsiprenumeruokite naujienlaiškį — pranešime jums!","product_tax_note":"PVM įskaičiuotas · pristatymas apskaičiuojamas atsiskaitant"},
  mt: {"added":"Miżjud","chat_error":"Żball.","chat_connection_error":"Żball fil-konnessjoni. Jekk jogħġbok erġa' pprova.","back_to_top":"Lura fil-quċċata","product_unavailable":"Il-prodott għadu mhux disponibbli","cart_demo_note":"Stripe qiegħed f'modalità ta' wirja:","err_name_reason_required":"L-isem u r-raġuni huma obbligatorji.","err_reason_min":"Ir-raġuni trid tkun mill-inqas 30 karattru.","err_invalid_email":"Indirizz tal-email mhux validu.","edukacio_intro":"Saħħa tan-nisa, terapija bis-sħana, għarfien tagħek innifsek. Artikli ċari, ibbażati fuq sorsi. EBC Wellness — għarfien indipendenti u b'xejn.","edukacio_empty":"Għad m'hemm l-ebda artiklu ppubblikat f'din il-kategorija. Abbona għan-newsletter — ngħarrfuk!","product_tax_note":"VAT inkluża · it-trasport jiġi kkalkulat fil-checkout"},
  sl: {"added":"Dodano","chat_error":"Napaka.","chat_connection_error":"Napaka povezave. Poskusite znova.","back_to_top":"Nazaj na vrh","product_unavailable":"Izdelek še ni na voljo","cart_demo_note":"Stripe je v predstavitvenem načinu:","err_name_reason_required":"Ime in razlog sta obvezna.","err_reason_min":"Razlog mora vsebovati vsaj 30 znakov.","err_invalid_email":"Neveljaven e-poštni naslov.","edukacio_intro":"Žensko zdravje, toplotna terapija, samozavedanje. Jasni članki, podprti z viri. EBC Wellness — neodvisno, brezplačno znanje.","edukacio_empty":"V tej kategoriji še ni objavljenih člankov. Naročite se na e-novice — obvestili vas bomo!","product_tax_note":"DDV vključen · stroški pošiljanja se izračunajo ob zaključku nakupa"},
};

export function getUi(locale: Locale): UiStrings {
  return UI_STRINGS[locale] ?? UI_STRINGS.en;
}
